server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para crear una reserva (/reserva)
    location /reserva {
        proxy_pass http://Restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com/reserva;
        proxy_http_version 1.1;
        proxy_set_header Host Restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy para listar las reservas (/reservas)
    location /reservas {
        proxy_pass http://Restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com/reservas;
        proxy_http_version 1.1;
        proxy_set_header Host Restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}