server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend real: http://restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com
    location = /reserva {
        proxy_pass http://restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com/reserva;
        proxy_http_version 1.1;
        proxy_set_header Host restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }

    location = /reservas {
        proxy_pass http://restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com/reservas;
        proxy_http_version 1.1;
        proxy_set_header Host restaurante-v2-env.eba-yimwd639.us-east-2.elasticbeanstalk.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }
}
