name: Deploy Frontend a Google Cloud Run

on:
  push:
    branches:
      - main

# ⚠️ SÚPER CRÍTICO: GitHub necesita estos permisos para poder pedirle el token temporal a Google Cloud
permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: project-c37db799-6063-4bcf-835
  SERVICE_NAME: git-practica-cloud-aws
  REGION: us-west1

jobs:
  deploy-frontend:
    name: Deploy HTML → Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Autenticar en GCP SIN ARCHIVO JSON 🎉
      - name: Autenticar en GCP (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          # Reemplaza el número de proyecto "194727093142" si tu número de proyecto es diferente
          workload_identity_provider: 'projects/194727093142/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'TU_CUENTA_DE_SERVICIO@project-c37db799-6063-4bcf-835.iam.gserviceaccount.com'

      # 3. Configurar gcloud CLI
      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 4. Construir y subir la imagen Docker
      - name: Build y Push imagen Docker
        run: |
          gcloud builds submit \
            --tag us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/restaurante/frontend:${{ github.sha }} \
            .

      # 5. Desplegar en Cloud Run
      - name: Deploy a Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image us-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/restaurante/frontend:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080